version: "2"
services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8810:80"
      - "4430:443"
    links:
      - jira
      - confluence
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
