version: "2"
volumes:
  db: ~
  jira: ~
  confluence: ~
services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links:
      - jira
      - confluence
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  confluence:
    restart: always
    build: ./confluence
    image: wobblecode/docker-confluence
    ports:
      - "8090:8090"
    links:
      - database
    volumes:
      - confluence:/var/atlassian/application-data/confluence
  jira:
    name: jira
    restart: always
    build: ./jira
    image: wobblecode/docker-jira
    ports:
      - "8080:8080"
    links:
      - database
    volumes:
      - jira:/var/atlassian/application-data/jira

  database:
    restart: always
    image: postgres:9.5
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
      - ./jira/setup-db.sh:/docker-entrypoint-initdb.d/setup-jira-db.sh
      - ./confluence/setup-db.sh:/docker-entrypoint-initdb.d/setup-confluence-db.sh
